version: "3.7"

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:

  # webui:
  #   build:
  #     context: ./webui
  #     dockerfile: Dockerfile.dev
  #     args: # from env_file
  #       IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
  #       PROXY_USER: ${PROXY_USER}
  #       PROXY_PASSWORD: ${PROXY_PASSWORD}
  #       PROXY_FQDN: ${PROXY_FQDN}
  #       PROXY_PORT: ${PROXY_PORT}
  #   env_file:
  #     - .env
  #   container_name: webui-dev
  #   security_opt:
  #     - no-new-privileges:true     
  #   ports:
  #     - "8080:3000"
  #   volumes:
  #     - ./webui:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPULLING=true

  stripe:
    build:
      context: ./stripe
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-stripe-dev
    privileged: true
    security_opt:
      - no-new-privileges:true     
    ports:
      - "8181:3111"
    volumes:
      - ./stripe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPULLING=true
